### ISSUE TITLE
Road 2 G.A. (1.0.0)

### ISSUE THREAD

**Issue by KarasuTatehi** [KarasuTatehi/ugonf#6]
## 概要
- 原則として、新機能の追加は行わないものとする

## ToDo
- [x] [喫茶ユゴス](https://w.atwiki.jp/cafe-yuggoth/)への初期サポート
- [x] 1週間の試験運用とバグ修正
  - [x] 追加: 送信開始・停止ボタン
  - [x] 追加: カメラセーフティ機能
  - [x] 変更: 映像解像度
  - [x] 修正: `MediaStream` 管理 => #9
    - [x] 問題: #1
  - [x] 修正: `MediaDeviceInfo` 管理 => #9
    - [x] 問題: #7
  - [x] 修正: ソースコード全体 => #9
- [x] ドキュメント作成 => 86c5b08

**Comment by KarasuTatehi** [comment]
ドキュメント作成 Done => 86c5b08

**Comment by KarasuTatehi** [comment]
立飛カラス「4:3より16:9のほうがやっぱり良い？」

**Comment by KarasuTatehi** [comment]
> 宮古ミーゴ「カメラ事前に選択するまでは、映らないようにしてほしい」

Done

**Comment by KarasuTatehi** [comment]
タスク Done
